INSERT INTO songs
(title, levels, inst_id)
VALUES('get white belt', 1,1),
('my first solo', 2, 1),
('evening song', 2, 1),
('scouts march', 3, 1),
('march melody', 3, 1),
('song of the wind',4,1),
('lightly row',4,1),
('may song',4,1),
('long, long ago', 5,1),
('allero', 5,1),
('in church',6,1),
('morning song', 6, 1),
('allegretto', 7, 1),
('andantino',7,1),
('minuet no1',8,1),
('surprise symphony theme',8,1),
('twilight serenade',9,1),
('minuet no2',9,1),
('gavotte', 10,1)